export const HEADER_COLLAPSED = 'HEADER_COLLAPSED'
export const HEADER_HELP_TOGGLED = 'HEADER_HELP_TOGGLED'
export const HEADER_USER_TOGGLED = 'HEADER_USER_TOGGLED'
export const HEADER_SEARCH_FORM_DISPLAY = 'HEADER_SEARCH_FORM_DISPLAY'